[2025-07-15T19:50:52.115+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_failure_sensor.perform_task manual__2025-07-15T19:50:49.979193+00:00 [queued]>
[2025-07-15T19:50:52.120+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_failure_sensor.perform_task manual__2025-07-15T19:50:49.979193+00:00 [queued]>
[2025-07-15T19:50:52.120+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-15T19:50:52.126+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): perform_task> on 2025-07-15 19:50:49.979193+00:00
[2025-07-15T19:50:52.128+0000] {standard_task_runner.py:57} INFO - Started process 4883 to run task
[2025-07-15T19:50:52.130+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_failure_sensor', 'perform_task', 'manual__2025-07-15T19:50:49.979193+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/failure_sensor_dag.py', '--cfg-path', '/tmp/tmp4czpqek4']
[2025-07-15T19:50:52.131+0000] {standard_task_runner.py:85} INFO - Job 106: Subtask perform_task
[2025-07-15T19:50:52.150+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_failure_sensor.perform_task manual__2025-07-15T19:50:49.979193+00:00 [running]> on host 1e79179934e4
[2025-07-15T19:50:52.189+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_failure_sensor' AIRFLOW_CTX_TASK_ID='perform_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T19:50:49.979193+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T19:50:49.979193+00:00'
[2025-07-15T19:50:52.189+0000] {logging_mixin.py:150} INFO - Running after FAILURE of ETL DAG!
[2025-07-15T19:50:52.189+0000] {logging_mixin.py:150} INFO - Current time: 2025-07-15 19:50:52.189574
[2025-07-15T19:50:52.189+0000] {python.py:183} INFO - Done. Returned value was: Failure message printed
[2025-07-15T19:50:52.198+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=etl_failure_sensor, task_id=perform_task, execution_date=20250715T195049, start_date=20250715T195052, end_date=20250715T195052
[2025-07-15T19:50:52.230+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-15T19:50:52.244+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
