[2025-07-17T07:31:54.807+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ops.upload_task manual__2025-07-17T07:31:53.832653+00:00 [queued]>
[2025-07-17T07:31:54.810+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ops.upload_task manual__2025-07-17T07:31:53.832653+00:00 [queued]>
[2025-07-17T07:31:54.811+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-07-17T07:31:54.817+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_task> on 2025-07-17 07:31:53.832653+00:00
[2025-07-17T07:31:54.819+0000] {standard_task_runner.py:57} INFO - Started process 1870 to run task
[2025-07-17T07:31:54.820+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ops', 'upload_task', 'manual__2025-07-17T07:31:53.832653+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/data_ops.py', '--cfg-path', '/tmp/tmp5tclpu3r']
[2025-07-17T07:31:54.821+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask upload_task
[2025-07-17T07:31:54.842+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ops.upload_task manual__2025-07-17T07:31:53.832653+00:00 [running]> on host 515ade4cdc0f
[2025-07-17T07:31:54.876+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ops' AIRFLOW_CTX_TASK_ID='upload_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T07:31:53.832653+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-17T07:31:53.832653+00:00'
[2025-07-17T07:31:54.877+0000] {logging_mixin.py:150} INFO - message: dag_id='dbt_build_monolith' command='upload' date_time='2025-07-17T07:31:53.695424+00:00'
[2025-07-17T07:31:54.879+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ops.py", line 65, in execute
    process_message(ConfigMessage.parse_obj(conf), context['dag'])
  File "/opt/airflow/dags/data_ops.py", line 49, in process_message
    if current_time - last_run_time < minimum_diff:
TypeError: can't subtract offset-naive and offset-aware datetimes
[2025-07-17T07:31:54.882+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=data_ops, task_id=upload_task, execution_date=20250717T073153, start_date=20250717T073154, end_date=20250717T073154
[2025-07-17T07:31:54.887+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 15 for task upload_task (can't subtract offset-naive and offset-aware datetimes; 1870)
[2025-07-17T07:31:54.919+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-17T07:31:54.927+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
