[2025-07-15T19:41:15.632+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_failure_sensor.perform_task manual__2025-07-15T19:41:12.412193+00:00 [queued]>
[2025-07-15T19:41:15.637+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_failure_sensor.perform_task manual__2025-07-15T19:41:12.412193+00:00 [queued]>
[2025-07-15T19:41:15.637+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-15T19:41:15.643+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): perform_task> on 2025-07-15 19:41:12.412193+00:00
[2025-07-15T19:41:15.645+0000] {standard_task_runner.py:57} INFO - Started process 3784 to run task
[2025-07-15T19:41:15.646+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_failure_sensor', 'perform_task', 'manual__2025-07-15T19:41:12.412193+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/failure_sensor_dag.py', '--cfg-path', '/tmp/tmp4irzo7p1']
[2025-07-15T19:41:15.647+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask perform_task
[2025-07-15T19:41:15.665+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_failure_sensor.perform_task manual__2025-07-15T19:41:12.412193+00:00 [running]> on host 1e79179934e4
[2025-07-15T19:41:15.701+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_failure_sensor' AIRFLOW_CTX_TASK_ID='perform_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T19:41:12.412193+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T19:41:12.412193+00:00'
[2025-07-15T19:41:15.701+0000] {logging_mixin.py:150} INFO - Running after FAILURE of ETL DAG!
[2025-07-15T19:41:15.701+0000] {logging_mixin.py:150} INFO - Current time: 2025-07-15 19:41:15.701887
[2025-07-15T19:41:15.701+0000] {python.py:183} INFO - Done. Returned value was: Failure message printed
[2025-07-15T19:41:15.711+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=etl_failure_sensor, task_id=perform_task, execution_date=20250715T194112, start_date=20250715T194115, end_date=20250715T194115
[2025-07-15T19:41:15.742+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-15T19:41:15.755+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
